export default {
    //`./assets/audio/${file_name}`
    "ali-cat.jpeg": require('./assets/images/ali-cat.jpeg'),
    "adventure-01": require('./assets/images/adventure-01.jpg'),
    "adventure-02": require('./assets/images/adventure-02.jpg'),
    "adventure-03": require('./assets/images/adventure-03.jpg'),
    "adventure-04": require('./assets/images/adventure-04.jpg'),
    "adventure-05": require('./assets/images/adventure-05.jpg'),
    "adventure-06": require('./assets/images/adventure-06.jpg'),
    "adventure-07": require('./assets/images/adventure-07.jpg'),
    "adventure-08": require('./assets/images/adventure-08.jpg'),
    "adventure-09": require('./assets/images/adventure-09.jpg'),
    "adventure-10": require('./assets/images/adventure-10.jpg'),
    "adventure-11": require('./assets/images/adventure-11.jpg'),
    "adventure-12": require('./assets/images/adventure-12.jpg'),
    // "adventure-13": require('./assets/images/adventure-13.jpg'),
    // "adventure-14": require('./assets/images/adventure-14.jpg'),
    // "adventure-15": require('./assets/images/adventure-15.jpg'),
    // "adventure-16": require('./assets/images/adventure-16.jpg'),
    "adventure-17": require('./assets/images/adventure-17.jpg'),
    // "adventure-18": require('./assets/images/adventure-18.jpg'),
    // "adventure-19": require('./assets/images/adventure-19.jpg'),
    // "adventure-20": require('./assets/images/adventure-20.jpg'),
    "adventure-21": require('./assets/images/adventure-21.jpg'),
    "adventure-22": require('./assets/images/adventure-22.jpg'),
    "adventure-23": require('./assets/images/adventure-23.jpg'),
    // "adventure-24": require('./assets/images/adventure-24.jpg'),
}